### ISSUE TITLE
Improve this page link not found 

### ISSUE THREAD

**Issue by AjRadwan** [Southampton-RSG-Training/workshop-template#10]
**when clicking on the button Improve this page not found**
 

![image](https://user-images.githubusercontent.com/43091820/151325064-0844c7c6-d40a-467c-b84d-a21d29773806.png)

**Comment by PipGrylls** [comment]
This is fixed now it links back to the template, it used to go to the lesson but the building structure now prevents that. IT makes sense for it to go to the template.
