### ISSUE TITLE
Schedule formatting incorrectly

### ISSUE THREAD

**Issue by PipGrylls** [Southampton-RSG-Training/workshop-template#12]
The schedule should go from top to bottom then move to the second column in date (then time) order. Sometimes I get [this ](https://southampton-rsg-training.github.io/DC-Demo/)
![Screenshot 2022-01-27 at 16 27 53](https://user-images.githubusercontent.com/22835635/151401159-c686f273-9ada-4985-9b68-853e4d0231e1.png)

**Comment by Edward-RSE** [comment]
Bit of a weird one, because this only happened if your browser window was wide enough. Fixed by making each row of the schedule list its own distinct div.

**Comment by PipGrylls** [comment]
> Bit of a weird one, because this only happened if your browser window was wide enough. Fixed by making each row of the schedule list its own distinct div.

Mobile-first development eh
