### ISSUE TITLE
Using the permalink configuration setting make sure lesson pages are built with a unique name.

### ISSUE THREAD

**Issue by PipGrylls** [Southampton-RSG-Training/workshop-template#4]
Detail: 
In line 17 in _config.yml the permalink option should define the creation of pages in the collections ':name' should give the collection name and ':title' the title of the .md specified in the document frontmatter. however at the moment we get ':name-:name' which means document frontmatter isn't being read? also :name is the name of the .md document and not the collection e.g. python-novice.

**Comment by Edward-RSE** [comment]
The solution we settled on is to set the slug in the front matter, and to use that as the permalink. The style of the slug is something like "shell-novice-introducing-the-shell" or "git-novice-setting-up-git".
